# -*- coding: utf-8 -*-
"""Finance-App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W53ZVw--dlxINGtJ-rgAnR_mbnYNKc0V
"""

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Commented out IPython magic to ensure Python compatibility.
#%config InlineBackend.figure_format = 'svg'
# %config InlineBackend.figure_format = 'retina'

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

plt.rc('figure', figsize=(8, 6))
#plt.style.use('seaborn')
#sns.set_style('whitegrid')
sns.set_style('white')

from matplotlib import rcParams
plt.rcParams["figure.autolayout"] = True
#rcParams['lines.linewidth'] = 2
#rcParams['lines.color'] = 'r'
#rcParams['savefig.dpi'] = 300
#rcParams['font.family'] = 'serif'

import numpy as np
np.set_printoptions(precision=4, suppress=True)

import pandas as pd
pd.options.display.max_rows = 12

"""

|Confidence Level |Two sided CV   |One sided CV   |
|---|---|---|
| 90%  |1.64   |1.28   |  
| 95%  |1.96   |1.64   |  
| 99%  |2.58   |2.33   |
"""

def spa():
  print('\n')
  return

"""https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.norm.html#scipy.stats.norm"""

import scipy as sp
from scipy.stats import norm

#@title Portfolio Setup
STOCK_TICKERS = 'AAPL,TSLA,MSFT' #@param {type:"string"}
PORTFOLIO_INITIAL_VALUE = 1000000 #@param {type:"number"}

# Optional: Override calculated expected return and volatility
# Leave blank to calculate from historical data
MANUAL_EXPECTED_RETURN_PCT = 15  #@param {type:"number"}
MANUAL_VOLATILITY_PCT = 27.49   #@param {type:"number"}

TRADING_DAYS_HORIZON = 21 #@param {type:"number"}

!pip install pandas-datareader
!pip install --upgrade pandas-datareader
import pandas_datareader as pdr

import yfinance as yf

tickers_list = [ticker.strip() for ticker in STOCK_TICKERS.split(',') if ticker.strip()]

if not tickers_list:
    raise ValueError("No tickers provided. Please enter at least one ticker symbol.")

# For simplicity, let's assume equal weights for now.
# User can modify this later.
weights = np.array([1/len(tickers_list)] * len(tickers_list))

# Fetch historical data (e.g., last year of daily closing prices)
end_date = pd.Timestamp.now()
start_date = end_date - pd.DateOffset(years=1) # Fetch 1 year of historical data for returns
print(f"Fetching historical data for {tickers_list} from {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")
historical_data = yf.download(tickers_list, start=start_date, end=end_date, auto_adjust=True)['Close']

if historical_data.empty:
    raise ValueError("Failed to download historical data for the given tickers. Please check symbols and try again.")
if historical_data.shape[1] != len(tickers_list):
    # This can happen if one ticker failed to download
    print(f"Warning: Data downloaded for {historical_data.shape[1]} out of {len(tickers_list)} tickers.")
    # Filter out tickers that don't have data
    downloaded_tickers = historical_data.columns.tolist()
    if len(downloaded_tickers) < len(tickers_list):
        print(f"Tickers with no data: {set(tickers_list) - set(downloaded_tickers)}. Adjusting portfolio.")
        tickers_list = downloaded_tickers
        if not tickers_list:
            raise ValueError("No valid tickers with historical data found.")
        weights = np.array([1/len(tickers_list)] * len(tickers_list))


# Calculate daily logarithmic returns
log_returns = np.log(historical_data / historical_data.shift(1)).dropna()

# Ensure weights align with available log returns columns
log_returns = log_returns[tickers_list]


# Calculate portfolio daily returns
# Dot product of daily returns and weights for each day
portfolio_daily_returns = (log_returns * weights).sum(axis=1)

# Calculate portfolio mean daily return and daily standard deviation
portfolio_daily_er = portfolio_daily_returns.mean()
portfolio_daily_volatility = portfolio_daily_returns.std()

# Annualize the portfolio mean return and volatility
# Assuming 252 trading days in a year
er_calculated = portfolio_daily_er * 252
volatility_calculated = portfolio_daily_volatility * np.sqrt(252)

# Apply manual overrides if provided
er = er_calculated
volatility = volatility_calculated

er_source = "Calculated"
volatility_source = "Calculated"

if MANUAL_EXPECTED_RETURN_PCT is not None:
    er = MANUAL_EXPECTED_RETURN_PCT / 100
    er_source = "Manual Override"

if MANUAL_VOLATILITY_PCT is not None:
    volatility = MANUAL_VOLATILITY_PCT / 100
    volatility_source = "Manual Override"

# Set initial portfolio value
pv = PORTFOLIO_INITIAL_VALUE

# Parameters for the VaR simulation
t = TRADING_DAYS_HORIZON / 252  # Time horizon (e.g., 21 trading days / 252 trading days per year)
iterations = 50000

print(f"\n--- Portfolio Summary ---")
print(f"Tickers: {tickers_list}")
print(f"Weights (equal distribution): {weights}")
print(f"Initial Portfolio Value (pv): ${pv:,.2f}")
print(f"Portfolio Annualized Expected Return (er): {er:.4f} ({er_source})")
print(f"Portfolio Annualized Volatility: {volatility:.4f} ({volatility_source})")
print(f"VaR Time Horizon (t): {t:.4f} years ({int(t*252)} trading days)")
print(f"Monte Carlo Iterations: {iterations}")

import yfinance as yf
aapl_ticker = yf.Ticker('AAPL')
# Display the full information dictionary from yfinance as a replacement for get_quote_yahoo
aapl_ticker.info

"""#Below, let's simulate future values from Geometric Brownian Motion series."""

def VaR(pv, er, vol, T, iterations):
    end = pv * np.exp((er - .5 * vol ** 2) * T +
                     vol * np.sqrt(T) * np.random.standard_normal(iterations))
    ending_values = end - pv
    return ending_values

at_risk = VaR(pv, er, volatility, t, iterations)
at_risk

type(at_risk)

np.shape(at_risk)

np.ndim(at_risk)

at_risk.mean()

at_risk.std()

plt.hist(at_risk,bins=100)

percentiles = [1,5,10]
np.percentile(at_risk, percentiles)

"""### Enhanced Histogram with VaR Levels

Let's visualize the distribution of potential gains and losses (`at_risk`) and mark the calculated Value at Risk (VaR) levels directly on the histogram. This helps to interpret what the 1%, 5%, and 10% VaR values mean in the context of the simulated outcomes.
"""

plt.figure(figsize=(10, 6))
sns.histplot(at_risk, bins=100, kde=True, color='skyblue', edgecolor='black')

# Get the calculated VaR levels
var_1_percent = np.percentile(at_risk, 1)
var_5_percent = np.percentile(at_risk, 5)
var_10_percent = np.percentile(at_risk, 10)

# Add vertical lines for VaR levels
plt.axvline(var_1_percent, color='red', linestyle='--', label=f'1% VaR: {var_1_percent:,.2f}')
plt.axvline(var_5_percent, color='orange', linestyle='--', label=f'5% VaR: {var_5_percent:,.2f}')
plt.axvline(var_10_percent, color='green', linestyle='--', label=f'10% VaR: {var_10_percent:,.2f}')

plt.title(f'Distribution of Simulated Portfolio Value Changes for {STOCK_TICKERS}')
plt.xlabel('Change in Portfolio Value ($)')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""### Cumulative Distribution Function (CDF) Plot

A CDF plot is excellent for understanding VaR. It shows the probability that the portfolio change will be less than or equal to a certain value. The VaR levels can be read directly from this plot, making it very intuitive.
"""

plt.figure(figsize=(10, 6))
sns.ecdfplot(at_risk, color='blue', linewidth=2)

# Add horizontal and vertical lines for VaR levels on the CDF
plt.axhline(y=0.01, color='red', linestyle='--', label='1% VaR Level')
plt.axvline(x=var_1_percent, color='red', linestyle='--')

plt.axhline(y=0.05, color='orange', linestyle='--', label='5% VaR Level')
plt.axvline(x=var_5_percent, color='orange', linestyle='--')

plt.axhline(y=0.10, color='green', linestyle='--', label='10% VaR Level')
plt.axvline(x=var_10_percent, color='green', linestyle='--')

plt.title(f'CDF of Simulated Portfolio Value Changes for {STOCK_TICKERS}')
plt.xlabel('Change in Portfolio Value ($)')
plt.ylabel('Cumulative Probability')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""### Final Histogram: Full Distribution of Simulated Profit/Loss

This histogram provides an overall view of all simulated portfolio value changes, showing the frequency of both gains and losses across the entire range of outcomes.
"""

plt.figure(figsize=(12, 7))
sns.histplot(at_risk, bins=100, kde=True, color='purple', edgecolor='white')
plt.title(f'Full Distribution of Simulated Portfolio Profit/Loss for {STOCK_TICKERS}')
plt.xlabel('Change in Portfolio Value ($)')
plt.ylabel('Frequency')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.axvline(x=0, color='gray', linestyle=':', label='No Change') # Mark the zero line
plt.legend()
plt.show()

"""### Monte Carlo Price Path Plot

This plot visualizes individual simulated price paths over the specified time horizon. Each line represents one possible evolution of the portfolio's value, helping to illustrate the uncertainty and potential trajectories.
"""

# Define parameters for path simulation
num_paths = 100 # Number of individual paths to plot
num_steps = int(t * 252) # Number of steps within the time horizon (t days)
dt = t / num_steps # Time increment for each step

# Array to store all simulated paths
simulated_paths = np.zeros((num_steps + 1, num_paths))
simulated_paths[0] = pv # All paths start at the initial portfolio value

# Simulate paths
for i in range(num_paths):
    for j in range(1, num_steps + 1):
        # Geometric Brownian Motion formula for price path
        drift = (er - 0.5 * volatility**2) * dt
        diffusion = volatility * np.sqrt(dt) * np.random.standard_normal()
        simulated_paths[j, i] = simulated_paths[j-1, i] * np.exp(drift + diffusion)

# Plot the simulated paths
plt.figure(figsize=(12, 7))
plt.plot(simulated_paths)
plt.title(f'Monte Carlo Simulated Price Paths for {STOCK_TICKERS}')
plt.xlabel('Time Steps (Days)')
plt.ylabel('Portfolio Value ($)')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""### Core Risk Statistics Summary"""

summary_stats = {
    'Statistic': [
        'Mean Change in Portfolio Value',
        'Standard Deviation of Change',
        '1% Value at Risk (VaR)',
        '5% Value at Risk (VaR)',
        '10% Value at Risk (VaR)'
    ],
    'Value ($)': [
        at_risk.mean(),
        at_risk.std(),
        var_1_percent,
        var_5_percent,
        var_10_percent
    ]
}

risk_summary_df = pd.DataFrame(summary_stats)
risk_summary_df['Value ($)'] = risk_summary_df['Value ($)'].map('{:,.2f}'.format) # Format to 2 decimal places with comma separators
display(risk_summary_df)